# Generated by Django 4.0.4 on 2022-06-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArquitectos', '0004_remove_avatar_imagen_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.DeleteModel(
            name='consulta',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
