# Generated by Django 4.0.4 on 2022-06-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArquitectos', '0005_remove_avatar_user_delete_consulta_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='imagen_edificio',
            field=models.ImageField(blank=True, null=True, upload_to='Imagen_Edificio'),
        ),
    ]
