# Generated by Django 4.0.4 on 2022-06-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArquitectos', '0006_edificio_imagen_edificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='imagen_ubicacion',
            field=models.ImageField(blank=True, upload_to='imagen_ubicacion'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='imagen_edificio',
            field=models.ImageField(blank=True, upload_to='Imagen_Edificio'),
        ),
    ]
